version: '3.1'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html/projectname:delegated # Must be modified for each project
    links:
      - php
    restart: always
  php:
    build:
      context: ./docker/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - web-data:/var/www/html/projectname:delegated # Must be modified for each project
      - /docker/php/php.ini-development:/usr/local/etc/php/php.ini
    links:
      - db
      - mail
      - redis
      - mercure
    depends_on:
      - db
    restart: always
  node:
    build:
      context: ./docker/node
    command: npm run dev-server
    working_dir: /usr/src/app
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
    restart: always
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
    volumes:
      - db-data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3306:3306"
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
    ports:
      - "81:80"
    links:
      - db
    depends_on:
      - db
  mail:
    image: maildev/maildev
    command: --hide-extensions STARTTLS
    ports:
      - 1080:1080
      - 1025:25
    restart: always
  redis:
    image: redis:5
    ports:
      - "6379:6379"
  mercure:
    image: dunglas/mercure
    environment:
      JWT_KEY: # Must be modified for each project
      PUBLISHER_JWT_KEY: # Must be modified for each project
      ALLOW_ANONYMOUS: 0
      CORS_ALLOWED_ORIGINS: 'http://projectname.localhost' # Must be modified for each project
    ports:
      - 8001:80

volumes:
  web-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/mael/Documents/Github/project-name' # Must be modified for each project
  db-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/mael/Documents/Github/project-name/.data/mysql' # Must be modified for each project
